In [4]:
import torch
import numpy as np

In [5]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones([3,3,4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
torch.Tensor([[1,2,3,4], [5,5,5,5], [6,7,8,9]])

tensor([[1., 2., 3., 4.],
        [5., 5., 5., 5.],
        [6., 7., 8., 9.]])

In [8]:
x = torch.Tensor([[1,2,3,4], [5,5,5,5], [6,7,8,9]])

In [9]:
x.size()

torch.Size([3, 4])

In [10]:
x.shape

torch.Size([3, 4])

In [11]:
x[2,3]

tensor(9.)

In [12]:
x[:,1]

tensor([2., 5., 7.])

In [13]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 15., 15., 15.],
        [16., 17., 18., 19.]])

In [14]:
x * 2

tensor([[ 2.,  4.,  6.,  8.],
        [10., 10., 10., 10.],
        [12., 14., 16., 18.]])

In [15]:
x ** 3

tensor([[  1.,   8.,  27.,  64.],
        [125., 125., 125., 125.],
        [216., 343., 512., 729.]])

In [16]:
y = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [17]:
x + y

tensor([[ 2.,  4.,  6.,  8.],
        [10., 11., 12., 13.],
        [15., 17., 19., 21.]])

In [18]:
x * y

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  30.,  35.,  40.],
        [ 54.,  70.,  88., 108.]])

In [19]:
x / y

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.8333, 0.7143, 0.6250],
        [0.6667, 0.7000, 0.7273, 0.7500]])

In [20]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 1.4841e+02, 1.4841e+02, 1.4841e+02],
        [4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03]])

In [21]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.9589, -0.9589, -0.9589],
        [-0.2794,  0.6570,  0.9894,  0.4121]])

In [22]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [23]:
mask = x > 3

In [24]:
x[x>3] #x[mask]

tensor([4., 5., 5., 5., 5., 6., 7., 8., 9.])

Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.

Входная матрица: X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Sample Input:

1
Sample Output:

tensor(44)

In [25]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X>limit].sum()

print(larger_than_limit_sum)

tensor(35)


In [26]:
y = x
y[0,0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   7.,   8.,   9.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   7.,   8.,   9.]])


In [27]:
x = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [28]:
y = x.clone()
y[0,0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [29]:
x.dtype

torch.float32

In [30]:
x = x.double()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)


In [31]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
x = torch.from_numpy(x)

In [33]:
x = torch.rand([2000,3000])
x

tensor([[0.8563, 0.4911, 0.6854,  ..., 0.7839, 0.6003, 0.6948],
        [0.1433, 0.9755, 0.8639,  ..., 0.6054, 0.6123, 0.7821],
        [0.8081, 0.2883, 0.6109,  ..., 0.0039, 0.2224, 0.9618],
        ...,
        [0.0714, 0.8410, 0.5441,  ..., 0.0249, 0.1971, 0.5946],
        [0.7039, 0.6874, 0.8518,  ..., 0.4062, 0.0732, 0.7226],
        [0.0274, 0.1015, 0.3410,  ..., 0.3466, 0.9274, 0.6106]])

In [39]:
torch.cuda.is_available()

False

In [35]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [36]:
x_cuda = x.to(device)
x_cuda

tensor([[0.8563, 0.4911, 0.6854,  ..., 0.7839, 0.6003, 0.6948],
        [0.1433, 0.9755, 0.8639,  ..., 0.6054, 0.6123, 0.7821],
        [0.8081, 0.2883, 0.6109,  ..., 0.0039, 0.2224, 0.9618],
        ...,
        [0.0714, 0.8410, 0.5441,  ..., 0.0249, 0.1971, 0.5946],
        [0.7039, 0.6874, 0.8518,  ..., 0.4062, 0.0732, 0.7226],
        [0.0274, 0.1015, 0.3410,  ..., 0.3466, 0.9274, 0.6106]])

In [37]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 19.3 ms, sys: 27.5 ms, total: 46.8 ms
Wall time: 14.2 ms


In [38]:
%time y = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 18.6 ms, sys: 14.9 ms, total: 33.5 ms
Wall time: 8.67 ms
