In [ ]:
%pip install torch
%pip install numpy

In [43]:
import torch
import numpy as np

In [3]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3,3,4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.Tensor([[1,2,3,4], [5,5,5,5], [6,7,8,9]])

tensor([[1., 2., 3., 4.],
        [5., 5., 5., 5.],
        [6., 7., 8., 9.]])

In [16]:
x = torch.Tensor([[1,2,3,4], [5,5,5,5], [6,7,8,9]])

In [10]:
x.size()

torch.Size([3, 4])

In [11]:
x.shape

torch.Size([3, 4])

In [13]:
x[2,3]

tensor(9.)

In [15]:
x[:,1]

tensor([2., 5., 7.])

In [17]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 15., 15., 15.],
        [16., 17., 18., 19.]])

In [18]:
x * 2

tensor([[ 2.,  4.,  6.,  8.],
        [10., 10., 10., 10.],
        [12., 14., 16., 18.]])

In [19]:
x ** 3

tensor([[  1.,   8.,  27.,  64.],
        [125., 125., 125., 125.],
        [216., 343., 512., 729.]])

In [20]:
y = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [21]:
x + y

tensor([[ 2.,  4.,  6.,  8.],
        [10., 11., 12., 13.],
        [15., 17., 19., 21.]])

In [22]:
x * y

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  30.,  35.,  40.],
        [ 54.,  70.,  88., 108.]])

In [23]:
x / y

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.8333, 0.7143, 0.6250],
        [0.6667, 0.7000, 0.7273, 0.7500]])

In [24]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 1.4841e+02, 1.4841e+02, 1.4841e+02],
        [4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03]])

In [26]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.9589, -0.9589, -0.9589],
        [-0.2794,  0.6570,  0.9894,  0.4121]])

In [27]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [28]:
mask = x > 3

In [31]:
x[x>3] #x[mask]

tensor([4., 5., 5., 5., 5., 6., 7., 8., 9.])

Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.

Входная матрица: X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Sample Input:

1
Sample Output:

tensor(44)

In [33]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X>limit].sum()

print(larger_than_limit_sum)

tensor(44)


In [32]:
y = x
y[0,0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   7.,   8.,   9.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   7.,   8.,   9.]])


In [34]:
x = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [36]:
y = x.clone()
y[0,0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [41]:
x.dtype

torch.int64

In [42]:
x = x.double()
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.]], dtype=torch.float64)


In [46]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
x = torch.from_numpy(x)

In [62]:
x = torch.rand([2000,3000])
x

tensor([[0.9505, 0.1014, 0.0020,  ..., 0.0667, 0.6920, 0.5582],
        [0.2804, 0.5106, 0.7092,  ..., 0.5479, 0.2271, 0.0194],
        [0.8909, 0.1662, 0.9901,  ..., 0.7648, 0.6341, 0.1640],
        ...,
        [0.6300, 0.7666, 0.7930,  ..., 0.2122, 0.6662, 0.6988],
        [0.9227, 0.4846, 0.3938,  ..., 0.5652, 0.3859, 0.3880],
        [0.8697, 0.5768, 0.7803,  ..., 0.6631, 0.0763, 0.6437]])

In [63]:
torch.cuda.is_available()

False

In [64]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [65]:
x_cuda = x.to(device)
x_cuda

tensor([[0.9505, 0.1014, 0.0020,  ..., 0.0667, 0.6920, 0.5582],
        [0.2804, 0.5106, 0.7092,  ..., 0.5479, 0.2271, 0.0194],
        [0.8909, 0.1662, 0.9901,  ..., 0.7648, 0.6341, 0.1640],
        ...,
        [0.6300, 0.7666, 0.7930,  ..., 0.2122, 0.6662, 0.6988],
        [0.9227, 0.4846, 0.3938,  ..., 0.5652, 0.3859, 0.3880],
        [0.8697, 0.5768, 0.7803,  ..., 0.6631, 0.0763, 0.6437]])

In [66]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 4.16 ms, sys: 24 ms, total: 28.2 ms
Wall time: 28.6 ms


In [67]:
%time y = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 14.5 ms, sys: 16.5 ms, total: 31 ms
Wall time: 31.6 ms
